### ISSUE TITLE
Error when trying to fetch has_many association

### ISSUE THREAD

**Issue by ptarud** [mhgbrown/cached_resource#39]
When a cached resource is trying to fetch it has_many associations it crashed.

from /home/ptarud/.rvm/gems/ruby-2.4.0/gems/cached_resource-5.0.1/lib/cached_resource/caching.rb:91:in `new'
	from /home/ptarud/.rvm/gems/ruby-2.4.0/gems/cached_resource-5.0.1/lib/cached_resource/caching.rb:91:in `block in cache_read'
	from /home/ptarud/.rvm/gems/ruby-2.4.0/gems/activesupport-5.2.0/lib/active_support/core_ext/object/try.rb:16:in `try!'
	from /home/ptarud/.rvm/gems/ruby-2.4.0/gems/activesupport-5.2.0/lib/active_support/core_ext/object/try.rb:8:in `try'
	from /home/ptarud/.rvm/gems/ruby-2.4.0/gems/cached_resource-5.0.1/lib/cached_resource/caching.rb:87:in `cache_read'
	from /home/ptarud/.rvm/gems/ruby-2.4.0/gems/cached_resource-5.0.1/lib/cached_resource/caching.rb:36:in `find_via_cache'
	from /home/ptarud/.rvm/gems/ruby-2.4.0/gems/cached_resource-5.0.1/lib/cached_resource/caching.rb:23:in `find_with_cache'
	from /home/ptarud/.rvm/gems/ruby-2.4.0/gems/activeresource-5.0.0/lib/active_resource/associations.rb:150:in `block in defines_has_many_finder_method'

**Comment by Daniel-ltw** [comment]
Could you try debugging the code by putting in a binding or a debugger before line 90 in lib/cached_resource/caching.rb? 

This should help you get to something and understand why it is throwing that error. 
From what you shared, I am not really see what error is being thrown, so I cannot make sense of why it is throwing that error.

**Comment by jlurena** [comment]
This should be closed, is over 6 years old. Thoughts @mhgbrown ?

**Comment by mhgbrown** [comment]
Sounds goods.
